name: Deploy Frontend (Next.js)

on:
  push:
    branches:
      - main
      - deploy-front

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-front
      cancel-in-progress: true

    env:
      AWS_REGION: us-east-2 #Modificar
      S3_BUCKET: letterbox-movies-prod-2025 #Modificar
      CF_DIST_ID: E3VXJRORKU2FU7 #Modificar

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node (con cache pnpm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js static site
        run: pnpm run build && npx next export   # genera /out

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::3:role/Movies-letterbox-Prod #Modificar
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./out s3://${{ env.S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ env.CF_DIST_ID }} --paths "/*"
